### ISSUE TITLE
请问mykey是否会推出桌面端或浏览器插件？

### ISSUE THREAD

**Issue by lowesyang** [mykeylab/MYKEY-APP#15]
感谢推出Mykey这么优秀的钱包，基于以下几点希望mykey能推出桌面端或浏览器插件：
1. 能够让更多人在工作场景下"友好"地使用钱包。
2. 适配一些基于PC Web的重度链游。
3. 更精细化地管理账户和密钥，如直接复制密钥至硬盘等。
4. 便于开发者使用mykey进行调试。

**Comment by RickyShiJs** [comment]
感谢建议。

目前MYKEY还没有桌面端的浏览器插件的计划。

大概原因如下：

PC环境下的安全因素较多，相对于手机的沙盒环境有较多的外界和安全因素的干扰。
MYKEY也是面向小白用户，力求避免用户在私钥导入导出的过程中减少犯错的可能。
目前MYKEY在安卓端使用的是安全区，苹果端用的是Enclave用户的密钥数据，基础环境会相对更加可控安全。

当前和后续的工作
对于PC端，目前MYKEY已经支持了WalletConnect之类的协议，并且该协议也在不断增强，很多以太坊上的应用已经支持了桌面端访问使用，在移动端进行前面操作。

我们也有增加非资产临时operation key的计划，应用可以自行在pc端生成一个keypair，将公钥和MYKEY合约绑定，那么这个本地的key就可以无需密码的进行签名操作了。

**Comment by yyh1102** [comment]
Cool~ 临时 op key的想法很棒。

感觉桌面端或许可以做最精简处理，比如仅仅让用户导入一个op key即可。对于一些纯链上链游来说，使用过程需要频繁扫码签名和调合约，仍然是过于繁琐的。能够原生流畅地使用 Web Dapp才是最佳的体验。

对于日常使用来说，用户体验优先级应该高于安全因素，大资金也不会放进常用的联网钱包。
