### ISSUE TITLE
体验建议

### ISSUE THREAD

**Issue by qingyiqu** [mykeylab/MYKEY-APP#7]
转账过程中应该设置常用交易账号保存、最新交易账号记录。
另外来交易账号应该设置快捷转账按钮。这样不易输入账号错误。
其他更多更好体验

**Comment by RickyShiJs** [comment]
已安排优化，谢谢

**Comment by vincentlyl** [comment]
> 。

能否详细说明下交易账号快捷转账按钮的想法？谢谢。

**Comment by RickyShiJs** [comment]
已在0.1.2中增强
